version: "3.9"

services:
  web:
    build: .
    container_name: trabalho_web
    command: /entrypoint.sh
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=sistema_admin.settings
      - DEBUG=1
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - TZ=America/Sao_Paulo
    volumes:
      - .:/code
      - django_static:/code/app/staticfiles
      - django_media:/code/app/media
      - django_logs:/code/app/logs
    restart: unless-stopped

volumes:
  django_static:
  django_media:
  django_logs:
